{*********************************************************}
{*                    INKEY.INC 1.00                     *}
{*                   For Turbo Pascal                    *}
{*      Assorted conditional compilation directives      *}
{*                                                       *}
{*     Copyright (c) 'D M D Computer Co.'(Tm) 1996.      *}
{*              BULGARIA  8900  Nova Zagora              *}
{*                                                       *}
{*   and used under not license to TurboPower Software   *}
{*               All rights not reserved.                *}
{*********************************************************}

{$DEFINE K_UP                5  }
{$DEFINE K_DOWN             24  }
{$DEFINE K_LEFT             19  }
{$DEFINE K_RIGHT             4  }
{$DEFINE K_HOME              1  }
{$DEFINE K_END               6  }
{$DEFINE K_PGUP             18  }
{$DEFINE K_PGDN              3  }

{$DEFINE K_CTRL_UP         397  }
{$DEFINE K_CTRL_DOWN       401  }
{$DEFINE K_CTRL_LEFT        26  }
{$DEFINE K_CTRL_RIGHT        2  }
{$DEFINE K_CTRL_HOME        29  }
{$DEFINE K_CTRL_END         23  }
{$DEFINE K_CTRL_PGUP        31  }
{$DEFINE K_CTRL_PGDN        30  }

{$DEFINE K_ALT_UP          408  }
{$DEFINE K_ALT_DOWN        416  }
{$DEFINE K_ALT_LEFT        411  }
{$DEFINE K_ALT_RIGHT       413  }
{$DEFINE K_ALT_HOME        407  }
{$DEFINE K_ALT_END         415  }
{$DEFINE K_ALT_PGUP        409  }
{$DEFINE K_ALT_PGDN        417  }

{$DEFINE K_ENTER            13  }
{$DEFINE K_RETURN           13  }
{$DEFINE K_SPACE            32  }
{$DEFINE K_ESC              27  }

{$DEFINE K_CTRL_ENTER       10  }
{$DEFINE K_CTRL_RETURN      10  }
{$DEFINE K_CTRL_RET         10  }
{$DEFINE K_CTRL_PRTSCR     379  }
{$DEFINE K_CTRL_QUESTION   309  }

{$DEFINE K_ALT_ENTER       284  }
{$DEFINE K_ALT_RETURN      284  }
{$DEFINE K_ALT_EQUALS      387  }
{$DEFINE K_ALT_ESC         257  }



{$DEFINE KP_ALT_ENTER      422  }

{$DEFINE KP_CTRL_5         399  }
{$DEFINE KP_CTRL_SLASH     405  }
{$DEFINE KP_CTRL_ASTERISK  406  }
{$DEFINE KP_CTRL_MINUS     398  }
{$DEFINE KP_CTRL_PLUS      400  }

{$DEFINE KP_ALT_5            5  }
{$DEFINE KP_ALT_SLASH      420  }
{$DEFINE KP_ALT_ASTERISK   311  }
{$DEFINE KP_ALT_MINUS      330  }
{$DEFINE KP_ALT_PLUS       334  }



{$DEFINE K_INS              22  }
{$DEFINE K_DEL               7  }
{$DEFINE K_BS                8  }
{$DEFINE K_TAB               9  }
{$DEFINE K_SH_TAB          271  }

{$DEFINE K_CTRL_INS        402  }
{$DEFINE K_CTRL_DEL        403  }
{$DEFINE K_CTRL_BS         127  }
{$DEFINE K_CTRL_TAB        404  }

{$DEFINE K_ALT_INS         418  }
{$DEFINE K_ALT_DEL         419  }
{$DEFINE K_ALT_BS          270  }
{$DEFINE K_ALT_TAB         421  }



{$DEFINE K_CTRL_A        1      }
{$DEFINE K_CTRL_B        2      }
{$DEFINE K_CTRL_C        3      }
{$DEFINE K_CTRL_D        4      }
{$DEFINE K_CTRL_E        5      }
{$DEFINE K_CTRL_F        6      }
{$DEFINE K_CTRL_G        7      }
{$DEFINE K_CTRL_H        8      }
{$DEFINE K_CTRL_I        9      }
{$DEFINE K_CTRL_J       10      }
{$DEFINE K_CTRL_K       11      }
{$DEFINE K_CTRL_L       12      }
{$DEFINE K_CTRL_M       13      }
{$DEFINE K_CTRL_N       14      }
{$DEFINE K_CTRL_O       15      }
{$DEFINE K_CTRL_P       16      }
{$DEFINE K_CTRL_Q       17      }
{$DEFINE K_CTRL_R       18      }
{$DEFINE K_CTRL_S       19      }
{$DEFINE K_CTRL_T       20      }
{$DEFINE K_CTRL_U       21      }
{$DEFINE K_CTRL_V       22      }
{$DEFINE K_CTRL_W       23      }
{$DEFINE K_CTRL_X       24      }
{$DEFINE K_CTRL_Y       25      }
{$DEFINE K_CTRL_Z       26      }



{$DEFINE K_ALT_A         286    }
{$DEFINE K_ALT_B         304    }
{$DEFINE K_ALT_C         302    }
{$DEFINE K_ALT_D         288    }
{$DEFINE K_ALT_E         274    }
{$DEFINE K_ALT_F         289    }
{$DEFINE K_ALT_G         290    }
{$DEFINE K_ALT_H         291    }
{$DEFINE K_ALT_I         279    }
{$DEFINE K_ALT_J         292    }
{$DEFINE K_ALT_K         293    }
{$DEFINE K_ALT_L         294    }
{$DEFINE K_ALT_M         306    }
{$DEFINE K_ALT_N         305    }
{$DEFINE K_ALT_O         280    }
{$DEFINE K_ALT_P         281    }
{$DEFINE K_ALT_Q         272    }
{$DEFINE K_ALT_R         275    }
{$DEFINE K_ALT_S         287    }
{$DEFINE K_ALT_T         276    }
{$DEFINE K_ALT_U         278    }
{$DEFINE K_ALT_V         303    }
{$DEFINE K_ALT_W         273    }
{$DEFINE K_ALT_X         301    }
{$DEFINE K_ALT_Y         277    }
{$DEFINE K_ALT_Z         300    }
{$DEFINE K_ALT_1         376    }
{$DEFINE K_ALT_2         377    }
{$DEFINE K_ALT_3         378    }
{$DEFINE K_ALT_4         379    }
{$DEFINE K_ALT_5         380    }
{$DEFINE K_ALT_6         381    }
{$DEFINE K_ALT_7         382    }
{$DEFINE K_ALT_8         383    }
{$DEFINE K_ALT_9         384    }
{$DEFINE K_ALT_0         385    }



{$DEFINE K_F1           28      }
{$DEFINE K_F2           -1      }
{$DEFINE K_F3           -2      }
{$DEFINE K_F4           -3      }
{$DEFINE K_F5           -4      }
{$DEFINE K_F6           -5      }
{$DEFINE K_F7           -6      }
{$DEFINE K_F8           -7      }
{$DEFINE K_F9           -8      }
{$DEFINE K_F10          -9      }
{$DEFINE K_F11         -40      }
{$DEFINE K_F12         -41      }



{$DEFINE K_CTRL_F1       -20    }
{$DEFINE K_CTRL_F2       -21    }
{$DEFINE K_CTRL_F3       -22    }
{$DEFINE K_CTRL_F4       -23    }
{$DEFINE K_CTRL_F5       -24    }
{$DEFINE K_CTRL_F6       -25    }
{$DEFINE K_CTRL_F7       -26    }
{$DEFINE K_CTRL_F8       -27    }
{$DEFINE K_CTRL_F9       -28    }
{$DEFINE K_CTRL_F10      -29    }
{$DEFINE K_CTRL_F11      -44    }
{$DEFINE K_CTRL_F12      -45    }



{$DEFINE K_ALT_F1       -30     }
{$DEFINE K_ALT_F2       -31     }
{$DEFINE K_ALT_F3       -32     }
{$DEFINE K_ALT_F4       -33     }
{$DEFINE K_ALT_F5       -34     }
{$DEFINE K_ALT_F6       -35     }
{$DEFINE K_ALT_F7       -36     }
{$DEFINE K_ALT_F8       -37     }
{$DEFINE K_ALT_F9       -38     }
{$DEFINE K_ALT_F10      -39     }
{$DEFINE K_ALT_F11      -46     }
{$DEFINE K_ALT_F12      -47     }



{$DEFINE K_SH_F1       -10      }
{$DEFINE K_SH_F2       -11      }
{$DEFINE K_SH_F3       -12      }
{$DEFINE K_SH_F4       -13      }
{$DEFINE K_SH_F5       -14      }
{$DEFINE K_SH_F6       -15      }
{$DEFINE K_SH_F7       -16      }
{$DEFINE K_SH_F8       -17      }
{$DEFINE K_SH_F9       -18      }
{$DEFINE K_SH_F10      -19      }
{$DEFINE K_SH_F11      -42      }
{$DEFINE K_SH_F12      -43      }
