{*********************************************************}
{*                  INKEY.INC 1.01/rev.                  *}
{*                   For Turbo Pascal                    *}
{*      Assorted conditional compilation directives      *}
{*                                                       *}
{*     Copyright (c) 'D M D Computer Co.'(Tm) 1996.      *}
{*              BULGARIA  8900  Nova Zagora              *}
{*                                                       *}
{*   and used under not license to TurboPower Software   *}
{*               All rights not reserved.                *}
{*********************************************************}

{$DEFINE K_UP                5  }
{$DEFINE K_DOWN             24  }
{$DEFINE K_LEFT             19  }
{$DEFINE K_RIGHT             4  }
{$DEFINE K_HOME              1  }
{$DEFINE K_END               6  }
{$DEFINE K_PGUP             18  }
{$DEFINE K_PGDN              3  }

{$DEFINE K_ENTER            13  }
{$DEFINE K_RETURN           13  }
{$DEFINE K_SPACE            32  }
{$DEFINE K_ESC              27  }

{$DEFINE KP_CTRL_5         399  }
{$DEFINE KP_CTRL_SLASH     405  }
{$DEFINE KP_CTRL_ASTERISK  406  }
{$DEFINE KP_CTRL_MINUS     398  }
{$DEFINE KP_CTRL_PLUS      400  }

{$DEFINE KP_ALT_5            5  }
{$DEFINE KP_ALT_SLASH      420  }
{$DEFINE KP_ALT_ASTERISK   311  }
{$DEFINE KP_ALT_MINUS      330  }
{$DEFINE KP_ALT_PLUS       334  }

{$DEFINE K_INS              22  }
{$DEFINE K_DEL               7  }
{$DEFINE K_BS                8  }
{$DEFINE K_TAB               9  }
{$DEFINE K_SH_TAB          271  }

{$DEFINE K_CTRL_A        1      }
{$DEFINE K_CTRL_B        2      }
{$DEFINE K_CTRL_C        3      }
{$DEFINE K_CTRL_D        4      }
{$DEFINE K_CTRL_E        5      }
{$DEFINE K_CTRL_F        6      }
{$DEFINE K_CTRL_G        7      }
{$DEFINE K_CTRL_H        8      }
{$DEFINE K_CTRL_I        9      }
{$DEFINE K_CTRL_J       10      }
{$DEFINE K_CTRL_K       11      }
{$DEFINE K_CTRL_L       12      }
{$DEFINE K_CTRL_M       13      }
{$DEFINE K_CTRL_N       14      }
{$DEFINE K_CTRL_O       15      }
{$DEFINE K_CTRL_P       16      }
{$DEFINE K_CTRL_Q       17      }
{$DEFINE K_CTRL_R       18      }
{$DEFINE K_CTRL_S       19      }
{$DEFINE K_CTRL_T       20      }
{$DEFINE K_CTRL_U       21      }
{$DEFINE K_CTRL_V       22      }
{$DEFINE K_CTRL_W       23      }
{$DEFINE K_CTRL_X       24      }
{$DEFINE K_CTRL_Y       25      }
{$DEFINE K_CTRL_Z       26      }

{$DEFINE K_ALT_A         286    }
{$DEFINE K_ALT_B         304    }
{$DEFINE K_ALT_C         302    }
{$DEFINE K_ALT_D         288    }
{$DEFINE K_ALT_E         274    }
{$DEFINE K_ALT_F         289    }
{$DEFINE K_ALT_G         290    }
{$DEFINE K_ALT_H         291    }
{$DEFINE K_ALT_I         279    }
{$DEFINE K_ALT_J         292    }
{$DEFINE K_ALT_K         293    }
{$DEFINE K_ALT_L         294    }
{$DEFINE K_ALT_M         306    }
{$DEFINE K_ALT_N         305    }
{$DEFINE K_ALT_O         280    }
{$DEFINE K_ALT_P         281    }
{$DEFINE K_ALT_Q         272    }
{$DEFINE K_ALT_R         275    }
{$DEFINE K_ALT_S         287    }
{$DEFINE K_ALT_T         276    }
{$DEFINE K_ALT_U         278    }
{$DEFINE K_ALT_V         303    }
{$DEFINE K_ALT_W         273    }
{$DEFINE K_ALT_X         301    }
{$DEFINE K_ALT_Y         277    }
{$DEFINE K_ALT_Z         300    }
{$DEFINE K_ALT_1         376    }
{$DEFINE K_ALT_2         377    }
{$DEFINE K_ALT_3         378    }
{$DEFINE K_ALT_4         379    }
{$DEFINE K_ALT_5         380    }
{$DEFINE K_ALT_6         381    }
{$DEFINE K_ALT_7         382    }
{$DEFINE K_ALT_8         383    }
{$DEFINE K_ALT_9         384    }
{$DEFINE K_ALT_0         385    }

{$DEFINE K_F1           28      }
{$DEFINE K_F2           -1      }
{$DEFINE K_F3           -2      }
{$DEFINE K_F4           -3      }
{$DEFINE K_F5           -4      }
{$DEFINE K_F6           -5      }
{$DEFINE K_F7           -6      }
{$DEFINE K_F8           -7      }
{$DEFINE K_F9           -8      }
{$DEFINE K_F10          -9      }
{$DEFINE K_F11         -40      }
{$DEFINE K_F12         -41      }
