uses crt,graph;
var c:char;i:integer;
begin
 { textbackgraund(red);clrscr;
  textcolor(yellow);}
  for i:=1 to 3 do
  begin
    sound(260);
    delay(300);
  end;
  sound(330);
  delay(300);
  nosound;
  for i:=1 to 3 do
  begin
  sound(395);
  delay(300);
  nosound;
  sound(330);
  delay(300);
  nosound;
  for i:=1 to 2 do
  begin
  sound(285);
  delay(300);
  nosound;
  end;
  sound(330);
  delay(300);
  nosound;
  sound(285);
  delay(300);
  nosound;
  sound(260);
  delay(300);
  nosound;
  sound(330);
  delay(300);
  nosound;
  sound(395);
  delay(400);
  nosound;
  delay(1);
  for i:=1 to 3 do
  begin
  sound(260);
  delay(300);
  nosound;
  end;
  sound(330);
  delay(300);
  nosound;
  for i:=1 to 3 do
  begin
  sound(395);
  delay(300);
  nosound;
  end;
  sound(330);
  delay(300);
  nosound;
  for i:=1 to 2 do
  begin
  sound(285);
  delay(300);
  nosound;
  end;
  sound(330);
  delay(300);
  nosound;
  sound(280);
  delay(300);
  nosound;
  sound(260);
  delay(300);
  nosound;
  sound(330);
  delay(300);
  nosound;
  sound(260);
  delay(400);
  nosound;
  c:=readkey;
  end;
  end.
