*************************************** START

CLEAR
CLOSE ALL

SET CURSOR OFF

        DEFI WIND db_wss FROM 0 , 0 TO 24, 79 TITLE " ‘ˆ‘’…ŒŽ ‘šŽ™…ˆ… ! ";
                       'ÚÄÏÓÙÄÀÓ' FLOAT SHADOW COLOR SCHEME 8
        ACTIVATE WINDOW db_wss
        SET CURSOR OFF
        @ 10, 0 SAY ' ’Ž‚€ ŒŽ… ŠŽˆ… (€ Žƒ€Œ€’€ -COOP Standart- (tm)96) ‘’… Ž‹“—ˆ‹ˆ ‘€ŒŽ ‡€  '
        @ 12, 0 SAY '      „…ŒŽ‘’€–ˆŸ € ‚š‡ŒŽ†Ž‘’ˆ’… Œˆ, €ŠŽ „š†ˆ’… „€ €Ž’ˆ’… ‘ Œ…        '
        @ 14, 0 SAY '    ‘… Ž€„…’… € -DMD Computer.com- , £°. ®¢  ‡ £®° , ²¥«: 0457-23263      '
        @ 22, 0 SAY '     €’ˆ‘…’… Žˆ‡‚Ž‹… Š‹€‚ˆ˜, ‡€ „€ Ž„š‹†ˆ’… €Ž’€’€ ‘ ŠŽŒž’š€ ...  '
        INKEY(0)
        RELEASE WIND db_wss

SET COLOR TO
QUIT
RETURN

****************************************  END
