#INCLUDE "INKEY.HD"
cls

*****************************************

A=' DMD Computer.com (tm)&(c) 1995 , BULGARIA, Nova Zagora, +359 457 28024 '
B=' MJJ & PETER & DPP-to                                                   '

*****************************************************
*********  edit & print - shop information  *********
*****************************************************

*************************************************************************

SET COLOR TO N/BG+
@ 0,0,24,80 BOX 'ÅÅÅÅÅÅÅÅÅÅ'


@  3, 0 SAY 'ÅÅßßßßßßß Åßßß ÅÅÅßßß ßßß ÅÅÅÅÅÅÅÅÅÅÅÅßßßß ßßß ÅÅÅÅÅÅßßß ÅÅÅÅÅÅÅßßßß ÅÅßßßßßß ÅÅ'
@  4, 0 SAY 'Åßßß ÅÅßßß ßßß ÅÅßßß Åßßß ÅÅ(tm)`98ÅÅßßßßß ßßßß ÅÅÅÅßßßß ÅÅÅÅÅÅßßßßß ßßß ÅÅÅßßß '
@  5, 0 SAY 'Åßßß ÅÅÅÅÅÅßßß Åßßß ÅÅßßß ÅÅÅÅÅÅÅÅÅÅßßßßßß ßßßßß ÅÅßßßßß ÅÅÅÅÅßßßßßß ßßß ÅÅÅßßß '
@  6, 0 SAY 'ÅÅßßß ÅÅÅÅÅßßß ßßß ÅÅÅßßß ÅÅÅÅÅÅÅÅÅßßß ßßß ßßßßßßßßßßßßß ÅÅÅÅßßß ßßß ßßß ÅÅÅÅÅÅÅ'
@  7, 0 SAY 'ÅÅÅÅßßß ÅÅÅßßßßßß ÅÅÅÅßßß ÅÅÅÅÅÅÅÅßßß Åßßß ßßß Åßßß Åßßß ÅÅÅßßß Åßßß ßßß ÅÅÅÅÅÅÅ'
@  8, 0 SAY 'ÅÅÅÅÅÅßßß Åßßß ßßß ÅÅÅßßß ÅÅÅÅÅÅÅßßßßßßßßß ßßß ÅÅß ÅÅßßß ÅÅßßßßßßßßß ßßß ÅÅÅÅÅÅÅ'
@  9, 0 SAY 'ÅÅÅÅÅÅÅßßß ßßß Åßßß ÅÅßßß ÅÅÅÅÅÅßßß ÅÅÅßßß ßßß ÅÅÅÅÅÅßßß Åßßß ÅÅÅßßß ßßß ÅÛßßßß '
@ 10, 0 SAY 'Åßßß ÅÅßßß ßßß ÅÅßßß Åßßß ÅÅÅÅÅßßß ÅÅÅÅßßß ßßß ÅÅÅÅÅÅßßß ßßß ÅÅÅÅßßß ßßß ÅÅÅßßß '
@ 11, 0 SAY 'ÅÅßßßßßßß Åßßß ÅÅÅßßß ßßßßßßßßßßß ÅÅÅÅÅßßß ßßß ÅÅÅÅÅÅßßßßßß ÅÅÅÅÅßßß ÅÅßßßßßß ÅÅ'


@ 12, 13 SAY 'Åßßßßßßßßßßßßß ÅÅÅÅßßßß ÅÅÅÅÅÅÅßßßß ÅÅßßßßßßßßßßßßß ÅÅ'
@ 13, 13 SAY 'Åßßßß ÅÅÅÅÅÅßßßß ÅÅßßßßß ÅÅÅÅÅßßßßß ÅÅßßßß ÅÅÅÅÅÅßßßß '
@ 14, 13 SAY 'Åßßßß ÅÅÅÅÅÅßßßß ÅÅßßßßßß ÅÅÅßßßßßß ÅÅßßßß ÅÅÅÅÅÅßßßß '
@ 15, 13 SAY 'Åßßßß ÅÅÅÅÅÅßßßß ÅÅßßßßßßßßßßßßßßßß ÅÅßßßß ÅÅÅÅÅÅßßßß '
@ 16, 13 SAY 'Åßßßß ÅÅÅÅÅÅßßßß ÅÅßßßß Åßßßß Åßßßß ÅÅßßßß ÅÅÅÅÅÅßßßß '
@ 17, 13 SAY 'Åßßßß ÅÅÅÅÅÅßßßß ÅÅßßßß ÅÅßß ÅÅßßßß ÅÅßßßß ÅÅÅÅÅÅßßßß '
@ 18, 13 SAY 'Åßßßß ÅÅÅÅÅÅßßßß ÅÅßßßß ÅÅÅÅCOMPUTER.COM (tm)`95Åßßßß '
@ 19, 13 SAY 'Åßßßß ÅÅÅÅÅÅßßßß ÅÅßßßß ÅÅÅÅÅÅÅßßßß ÅÅßßßß ÅÅÅÅÅÅßßßß '
@ 20, 13 SAY 'Åßßßßßßßßßßßßß ÅÅÅÅßßßß ÅÅÅÅÅÅÅßßßß ÅÅßßßßßßßßßßßßß ÅÅ'


@ 21,1 SAY ' DMD Computer.com ÅÅÅ (c)98 ÅÅÅ SKLAMAG V 0.1 ÅÅÅ e-mail: root@newclass.net '
@ 22,1 SAY ' BULGARIA ÅÅ 8900 Nova Zagora ÅÅ p.k. 39 ÅÅ phones: ÅÅ +359 457 28024 '

CLEAR ALL
SET DATE GERMAN
SET MOUSE ON
SET MOUSE STYLE OFF
SET COLOR TO
CLOSE ALL
************************************






SET DATE GERMAN
SET INTENSITY ON

USE NOMEN_ST
IF FILE("NOMST.JTX")
        FERASE("NOMST.JTX")
ENDIF
INDEX ON NOM_ST TO NOMST
CLOSE DATABASE

USE NOMEN_MG
IF FILE("NOMMG.JTX")
        FERASE("NOMMG.JTX")
ENDIF
INDEX ON NOM_MAG TO NOMMG
CLOSE DATABASE


USE MONEY
IF FILE("MONY.JTX")
        FERASE("MONY.JTX")
ENDIF
INDEX ON DATA TO MONY
CLOSE DATABASE


USE SKLAD ALIAS SKLAD NEW
USE MAGAZIN ALIAS MAG NEW
USE NOMEN_ST INDEX NOMST ALIAS ST NEW
USE NOMEN_MG INDEX NOMMG ALIAS MG NEW
USE MONEY INDEX MONY ALIAS MONEY NEW


SELECT SKLAD
   pol:=     {'NOM_ST', 'IME_ST',  'MER_ST','KOL_ST','EDCP_ST','SUMA_ST','DATAP_ST','OS_ST',  'PEDC_ST','ZABEL'}
   polName :={'Õ','€ˆŒ…Ž‚€ˆ…','Œ.….','ŠŽ‹ˆ—…‘’‚Ž','…„.–…€','‘“Œ€','„€’€','€‹ˆ—Ž‘’', 'Ž„.–…€', '‡€…‹…†Š€'}

   DEFI WIND Win_ST FROM 2 ,1   TO 20 ,75 TITLE " ‘Š‹€„ ";
   'ðÍÑÍÈÇ' FLOAT SHADOW
   ACTIVATE WINDOW Win_ST

             DBEDIT( 0, 0,12,72,pol,'_dbfunc_auto',NIL,polname,"Ä"," ","Ä")
   RELEASE WINDOW Win_ST

SET COLOR TO W/N
CLEAR
CLOSE ALL
RETURN // EXIT PROGRAM
**************************** exit ***********************

FUNCTION _dbfunc_auto(mode,dPeek1)
  l_key := LASTKEY()  && —¥²¥¬ ¯®±«¥¤­¨¿² ­ ²¨±­ ² ª« ¢¨¸
  nROW := ROW()       &&  ¬¨° ¬¥ ªº¤¥ ¥ ¡¨« ¬ °ª¥° 
  nCOL := COL()       &&
  nreturn:=1
  DO CASE
     CASE  mode = 0
      @ (WROWS(WoUtput())-3),0 say space(74)
      @ (WROWS(WoUtput())-3),0 SAY ' ‡ ¯¨± ­®¬¥° '+STR(RECNO(),5) +'/' + LTRIM(STR(RECCOUNT()))+ ;
      " Š®«®­  "+ALLTRIM(str(ncol))+" ¥¤ "+ALLTRIM(str(nrow)) + '    [F1]-ŽŒŽ™ '

      @ (WROWS(WoUtput())-5),0 say '                 [CTRL+ENTER]-‚š‚…†„€… [ENTER]-ŠŽ…Š–ˆŸ                 '
      @ (WROWS(WoUtput())-6),0 say '[F5]-…ƒ‹…„_‘’ŽŠ€ [F6][F7][F8]-‘€‚Šˆ [F9]-Ž’—…’_€ˆ [F10]-…•‚š‹Ÿ…'

      @ (WROWS(WoUtput())-4),0 SAY 'ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ'
     CASE mode=1
        @ 1,2 SAY '„®±²¨£­ ²® ¥ ­ · «®²® ­  ´ ©« '
        INKEY(0)
        @ 1,2 SAY 'ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ'
        nreturn:=1
     CASE mode=2
        @ 1,2 SAY   '„®±²¨£­ ² ¥ ª° ¿ ­  ´ ©« .  '
        inkey(0)
        @ 1,2 SAY   'ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ'
        nreturn:=2
     CASE l_key = _del
       mmem = recno()
        DELETE
        PACK
        nRETURN = 2
        if recno() != lastrec()
           go mmem
        endif
     CASE  l_key = _ESC && EXIT <<--------------------------------
        nReturn := 0
*******************
     case l_key  = _CTRL_BS //  pol korekciq bree
          set cursor on
          PolpTemp  = POL[dPeek1]    &&  ‡ °¥¦¤ ¬¥ ¨¬¥­ ²  ­  ¯®«¥² ²  ®² ¬ ±¨¢ 
          @ nROW,  nCOL GET &PolpTemp  && ‘ ¬ ²  Š®°¥ª¶¨¿
          read
          tone(300,2)
          set cursor off
     CASE l_key  = _CTRL_RET .or. mode=3 && PAD ¢º¢¥¦¤ ­¥
        SET CURSOR ON
        SET ESCAPE ON
        set color to ,,,,,W+/N
        @ (WROWS(WoUtput())-3),0 SAY '  ¥¦¨¬ ‚º¢¥¦¤ ­¥ ­  ­®¢  ±²®ª .[F1]ˆ‘’“Š–ˆˆ [F2]”³ª¶¨®­ «­  ®¬®¹'
        @ (WROWS(WoUtput())-5),0 SAY space(60)
        go bottom
        append blank

   DEFI WIND WinAA FROM 2 ,4   TO 14 ,55 TITLE "‚º¢¥¦¤ ­¥ ­  ­®¢  ±²®ª ";
   'ðÍÑÍÈÇ' FLOAT SHADOW
   ACTIVATE WINDOW WinAA

        set color to ,,,,,W+/N

        SET KEY -1 TO Pluton // seen bot za nomenklaturata
        @ 1,2 SAY 'ŽŒ…       ' GET NOM_ST   WHEN(ONPLUTON()) VALID(SNOMER(NOM_ST))
        @ 2,2 SAY 'ˆŒ…         ' GET IME_ST   WHEN(OffPluton())
        @ 3,2 SAY 'Œ.….        ' GET MER_ST
        @ 4,2 SAY 'ŠŽ‹ˆ—…‘’‚Ž  ' GET KOL_ST   VALID(KOL_ST > 0)
        @ 5,2 SAY '…„.–…€     ' GET EDCP_ST  VALID(EDCP_ST > 0)
        @ 6,2 SAY '‘“Œ€        ' GET SUMA_ST  WHEN(SBOR())
        @ 7,2 SAY '„€’€        ' GET DATAP_ST
        @ 8,2 SAY 'Ž„.…„.–…€' GET PEDC_ST  VALID(PEDC_ST > 0)
        @ 9,2 SAY '‡€…‹E†Š€   ' GET ZABEL
        @ 10,2 SAY '[F2]-ŽŒ…Š‹€’“€_€_‘’ŽŠˆ’…'
        READ
        IF LASTKEY() = _ESC
                DELETE
                PACK
        set key -1
        ENDIF
        SET COLOR TO
        RELEASE WINDOW WinAA
        SET CURSOR OFF
        nReturn :=  2
        **********************************
        *---------------------------------------------------
        *************************************  korekciq .....
        CASE L_key = _RETURN  // korekciq
        SET CURSOR ON
        SET ESCAPE ON
        set color to ,,,,,W+/N
        @ (WROWS(WoUtput())-3),0 SAY '  ¥¦¨¬ Š®°¥£¨° ­¥ ­   ±²®ª .'
        @ (WROWS(WoUtput())-5),0 SAY space(60)

        DEFI WIND WinAA FROM 2 ,4   TO 14 ,55 TITLE "  Š®°¥£¨° ­¥ ­   ±²®ª   ";
        'ðÍÑÍÈÇ' FLOAT SHADOW
        ACTIVATE WINDOW WinAA
        set color to ,,,,,W+/N
        SET KEY -1 TO Pluton // seen bot za nomenklaturata
        pNOM_ST   = NOM_ST
        pIME_ST   = IME_ST
        pMER_ST   = MER_ST
        pKOL_ST   = KOL_ST
        pEDCP_ST  = EDCP_ST
        pSUMA_ST  = SUMA_ST
        pDATAP_ST = DATAP_ST
        pPEDC_ST  = PEDC_ST
        pOS_ST    = OS_ST
        pZABEL    = ZABEL
        @ 1,2 SAY 'ŽŒ…       ' GET NOM_ST   WHEN(ONPLUTON()) VALID(SNOMER(NOM_ST))
        @ 2,2 SAY 'ˆŒ…         ' GET IME_ST   WHEN(OffPluton())
        @ 3,2 SAY 'Œ.….        ' GET MER_ST
        @ 4,2 SAY 'ŠŽ‹ˆ—…‘’‚Ž  ' GET KOL_ST   VALID(KOL_ST  > 0)
        @ 5,2 SAY '…„.–…€     ' GET EDCP_ST  VALID(EDCP_ST > 0)
        @ 6,2 SAY '‘“Œ€        ' GET SUMA_ST  WHEN(K_SBOR(pKOL_ST,pOS_ST))
        @ 7,2 SAY '„€’€        ' GET DATAP_ST
        @ 8,2 SAY 'Ž„.…„.–…€' GET PEDC_ST  VALID(PEDC_ST > 0)
        @ 9,2 SAY '‡€…‹E†Š€   ' GET ZABEL
        READ
        if LastKey() = _ESC
           replace NOM_ST   with  pNOM_ST
           replace IME_ST   with  pIME_ST
           replace MER_ST   with  pMER_ST
           replace KOL_ST   with  pKOL_ST
           replace EDCP_ST  with  pEDCP_ST
           replace SUMA_ST  with  pSUMA_ST
           replace DATAP_ST with  pDATAP_ST
           replace PEDC_ST  with  pPEDC_ST
           replace OS_ST    with  pOS_ST
           replace ZABEL    with  pZABEL
           set key -1
        endif
        SET COLOR TO
        RELEASE WINDOW WinAA
        SET CURSOR OFF
        nReturn :=  2
        CASE L_key = _F10  // razpredelenie
             MAGAZIN()
             nReturn :=  2
        CASE L_key = _F9   // pari
             PARI()
             nReturn :=  2
        CASE L_key = _F5
             Pregled()
             nReturn := 2
        CASE L_key = _F6
             Spr_st_mag()
             nReturn := 2
        CASE L_key = _F7
             Spr_otpar_mag()
             nReturn := 2
        CASE L_key = _F8
             Spr_ostst_mag()
             nReturn := 2
        CASE mode = 5
             if MROW() > nRow .AND. MROW() != nRow  {  && Logic Mouse
             Sskip = MROW() - nRow -1
                skip Sskip
             else
             Sskip = nRow - MROW() +1
                skip -Sskip
             }
             nReturn := 1
        OTHERWISE
        nreturn:=1
       endCASE
return nReturn



**************************
****SBOR********
FUNCTION SBOR
REPLACE OS_ST WITH KOL_ST
REPLACE DATAP_ST WITH DATE()
REPLACE SUMA_ST WITH KOL_ST*EDCP_ST
RETURN .t.

**************************************

**************************
****K_SBOR********
FUNCTION K_SBOR(pkol,pos)
do case
   case OS_ST = KOL_ST
        REPLACE OS_ST WITH KOL_ST
        REPLACE SUMA_ST WITH KOL_ST*EDCP_ST
   case KOL_ST > pkol
        skolko = KOL_ST - pkol
        REPLACE OS_ST WITH OS_ST + skolko
        REPLACE SUMA_ST WITH KOL_ST*EDCP_ST
   case KOL_ST < pkol
        skolko = pkol - KOL_ST
        REPLACE OS_ST WITH OS_ST - skolko
        REPLACE SUMA_ST WITH KOL_ST*EDCP_ST
endcase
RETURN .t.
**************************************
****NOMER NA STOKA **********

FUNCTION SNOMER(_NOM)
sRETURN=.T.
IF _NOM =0
        sRETURN=.F.
ELSE
        SELECT ST
        GO TOP
        SEEK _NOM
        IF FOUND()
                vNOM_ST = NOM_ST
                vIME_ST = IME_ST
                vMER_ST = MER_ST
                SELECT SKLAD
                REPLACE NOM_ST WITH vNOM_ST
                REPLACE IME_ST WITH vIME_ST
                REPLACE MER_ST WITH vMER_ST
        ELSE
                sRETURN = .F.
        ENDIF
ENDIF

SELECT SKLAD

RETURN sRETURN
**************************************************
******** func ONPluton ****
FUNCTION ONPluton()
SET KEY -1 TO PLUTON()
RETURN .T.


**************************************************

**************************************************
******** func OffPluton ****
FUNCTION OffPluton()
SET KEY -1
RETURN .T.


**************************************************
******** func Pluton ****

FUNCTION Pluton()
private sime,lsREC,flg
sime = ""
lsREC = 0
flg=0

SET KEY -1
TRK = RECNO()
SELECT ST
   Pst :=    {'NOM_ST', 'IME_ST',  'MER_ST'}
   PNamest :={'Õ','€ˆŒ…Ž‚€ˆ…','Œ.….'}

   DEFI WIND WinPP FROM 4 ,40  TO 21 ,78 TITLE "ŽŒ…Š‹€’“€ ‘’ŽŠˆ";
   'ðÍÑÍÈÇ' FLOAT SHADOW
   ACTIVATE WINDOW WinPP
        DBEDIT( 1, 0,13,36,Pst,'dbePluton',NIL,PNamest,"Ä"," ","Ä")

   SELECT SKLAD
   GO TRK
   RELEASE WINDOW WinPP
   set cursor on
   SET KEY -1 TO Pluton()
RETURN .T.


**************************************************
******** func dbePluton ****
FUNCTION dbePluton(mode,dPeek1)
  l_key := LASTKEY()  && —¥²¥¬ ¯®±«¥¤­¨¿² ­ ²¨±­ ² ª« ¢¨¸
  nROW := ROW()       &&  ¬¨° ¬¥ ªº¤¥ ¥ ¡¨« ¬ °ª¥° 
  nCOL := COL()       &&
  nreturn:=1


  DO CASE
     CASE  mode = 0
      @ (WROWS(WoUtput())-4),0 say space(35)
      @ (WROWS(WoUtput())-4),0 SAY '‡ ¯¨± ­®¬¥° '+STR(RECNO(),5) +'/' + LTRIM(STR(RECCOUNT()))+ ;
      " Š®«®­  "+ALLTRIM(str(ncol))+" ¥¤ "+ALLTRIM(str(nrow))
      @ (WROWS(WoUtput())-5),0 SAY 'ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ'
     CASE mode=1
        @ 2,2 SAY '„®±²¨£­ ²® ¥ ­ · «®²® ­  ´ ©« '
        INKEY(0)
        @ 2,2 SAY 'ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ'
        nreturn:=1
     CASE mode=2
        @ 2,2 SAY   '„®±²¨£­ ² ¥ ª° ¿ ­  ´ ©« .  '
        inkey(0)
        @ 2,2 SAY   'ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ'
        nreturn:=2

     CASE  l_key = _ESC && EXIT <<--------------------------------
        nReturn := 0
*******************                ª® ¿¬  § ¯¨±¨ ¢º¢ ”€ˆ‹€ MMAIN1.DBF
     CASE  l_key = _RETURN
          P1NOM = NOM_ST
          P2IME = IME_ST
          P3MER = MER_ST
          SELECT SKLAD
          REPLACE NOM_ST WITH P1NOM
          REPLACE IME_ST WITH P2IME
          REPLACE MER_ST WITH P3MER
          nReturn := 0
     CASE  l_key = _DEL  // iztriva zapis posle sloji syobchteniq
           delete
           pack
           nReturn := 2

     CASE  l_key = _F3   // korekcija

        SELECT ST

        vNOM_ST = 0000
        vNOM_ST = NOM_ST
        vIME_ST = IME_ST
        vMER_ST = MER_ST

        DEFI WIND Win_STK FROM 4 ,20  TO 11 ,78 TITLE " ŠŽ…Š–ˆŸ ŽŒ…Š‹. ‘’ŽŠˆ ";
        'ðÍÑÍÈÇ' FLOAT SHADOW
        ACTIVATE WINDOW Win_STK

        SET CURSOR ON
        SET ESCAPE ON

        @ 1,0  SAY " ŽŒ… ‘’ŽŠ€       "  GET   vNOM_ST
        @ 2,0  SAY " ˆŒ… € ‘’ŽŠ€      "  GET   vIME_ST
        @ 3,0  SAY " Œ…€ …„ˆˆ–€     "  GET   vMER_ST
        READ

        RELEASE WINDOW Win_STK

        SET CURSOR OFF
        SET ESCAPE OFF
        IF LASTKEY() = _ESC
           nReturn := 0
           RETURN 0
        ENDIF

        IF LASTKEY != _ESC
        REPLACE NOM_ST WITH vNOM_ST
        REPLACE IME_ST WITH vIME_ST
        REPLACE MER_ST WITH vMER_ST
        ENDIF

        nReturn := 2


     CASE l_key  = _INS .or. mode=3 && PAD ¢º¢¥¦¤ ­¥
        savegets()
        SET CURSOR ON
        SET ESCAPE ON
        set color to ,,,,,W+/N

    **  DBEDIT( 0, 0,14,36,Pst,'dbePluton',NIL,PNamest,"Ä"," ","Ä")
        scroll(2,0,12,35,11)
        SELECT ST
        SET INDEX TO
        GO BOTTOM
        neda = 0
        neda = NOM_ST + 1
        SELECT ST
        SET INDEX TO NOMST
        APPEND BLANK

        REPLACE NOM_ST WITH neda
        ppNOM_ST = NOM_ST
        @ 2,2 SAY ' Ž‚€ ŽŒ…Š‹€’“€: '
        @ 3,2   GET ppNOM_ST valid(PRnom_ins(ppNOM_ST))
        @ 3,7   GET IME_ST
        @ 3,28  GET MER_ST
        READ
        @ 2,0 SAY 'ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ'
        replace NOM_ST with ppNOM_ST
        IF LASTKEY() = _ESC
                DELETE
                PACK
        ENDIF
        SET COLOR TO
        SET CURSOR off
        restgets()
  *     keyboard  chr(_up)+chr(_up)+chr(_up)+chr(_up)+chr(_up)+chr(_up)+chr(_up)+chr(_up)+chr(_up)
  *     keyboard chr(_down)+chr(_down)+chr(_down)+chr(_down)+chr(_down)+chr(_down)+chr(_down)+chr(_down)+chr(_down)
        **              1          2         3           4         5          6          7          8           9       10
        nreturn:=2

        OTHERWISE
        nreturn:=2
     endCASE
               if flg=2
                     flg=0
               endif
               if flg=1
                     flg=2
               endif
               if l_key >= 65 .and. l_key <= 191 .and. flg=0
                      sime = sime + CHR(l_key)
                      @ (WROWS(WoUtput())-3), 0 SAY "’º°±¥­¥: " + sime
                      go top
                      locate for IME_ST = sime
                      if found()
                          lsREC = RECNO()
                      else
                          go lsREC
                      endif
                      flg=1
               endif
               if flg=0 .or. len(sime) > 20
                       sime=""
                       @ (WROWS(WoUtput())-3),0 say space(35)
                       lsREC = RECNO()
               endif


return nReturn
*******************************************
******* funktion PRnom_ins(NOM_ST) // proverqva za dublirane na imena
FUNCTION PRnom_ins(tr_NOM)
pozres = recno()
pRETURN = .T.
locate for tr_NOM = NOM_ST
if found()
   pRETURN = .f.
*  ? found()
*  inkey(0)
   vz_error("„³¡«¨° ­¥ ­  ª®¤. OP ERROR","Œ®«¿ ª®°¥£¨° ©²¥ ..  ")
endif
go pozres
return pRETURN
*** end of functio seact nom


********************************************
****** vizual error
FUNCTION vz_error(nadpis1,nadpis2)
      x =  1 ; y = 25
      bs_n1 = len(nadpis1)
      bs_n2 = len(nadpis2)
      bs_n1 = (38 - bs_n1)/2
      bs_n2 = (38 - bs_n2)/2
      DEFI WIND WinSearcP FROM  x, y  TO x+3,y+38 TITLE " ƒ…˜Š€ ";
      'ðÍÑÄÀÓ'  FLOAT SHADOW
      ACTIVATE WINDOW WinSearcP
      ***********123456789012345678901234
      @ 0,bs_n1 say nadpis1
      @ 1,bs_n2 say nadpis2
***** SHOW
      FOR i:=0 to 11 {
           MOVE WINDOW WinSearcP BY 1,0
           inkey(0.01,"MH")
      }
      inkey(0,"MH")
      FOR i:=0 to 11 {
           MOVE WINDOW WinSearcP BY -1,0
      }
      RELEASE WINDOWS WinSearcP
return .t.





********* PETROVI PISANIA **MONOGO COPY/PASTE ‚š‡ŒŽ†ˆ ERRORS!!!!!*********
*********** DA SE PROVIRI DA LI WSICHKO RABOTI!************
***********MAGAZIN****************************
***Ž–…„“€ ‡€ €‡…„…‹…ˆ… € ‘’ŽŠˆ**********
**********************************************
PROCEDURE MAGAZIN()

   DEFI WIND Win_MG FROM 5 ,4   TO 20 ,55 TITLE " €‡…„…‹…ˆ… ";
   'ðÍÑÍÈÇ' FLOAT SHADOW
   ACTIVATE WINDOW Win_MG
   NOM_P = NOM_ST
   IME_P = IME_ST
   MER_P = MER_ST
   PEDC_P = PEDC_ST
   KOL_P = OS_ST
   SELECT MAG
   APPEND BLANK
   REPLACE NOM_ST WITH NOM_P
   REPLACE IME_ST WITH IME_P
   REPLACE MER_ST WITH MER_P
   REPLACE PEDC_ST WITH PEDC_P

   @0,1 SAY 'Ž…Š’ ŽŒ…:' GET NOM_MAG WHEN(ONBEHEPA()) VALID(MNOMER(NOM_MAG))
   @1,1 SAY 'ŠŽ‹ˆ—…‘’‚Ž:   ' GET KOL_ST  WHEN(OffBEHEPA()) VALID(KOL_ST > 0 .AND. KOL_ST <= KOL_P)
   @1,26 SAY 'Ž‘’€’šŠ:' + STR(KOL_P)
   @2,1 SAY 'Ž„.…„.–…€: ' GET PEDC_ST VALID(PEDC_ST>0)
   @3,1 SAY '‘“Œ€:         ' GET SUMA_ST WHEN(SUM_D())
   @4,1 SAY '„€’€:         ' GET DATAP_ST
   @5,1 SAY '‡€…‹…†Š€:    ' GET ZABEL
   READ
   OffBEHEPA()
   RELEASE WINDOW Win_MG
   IF LASTKEY() = _ESC
        DELETE
        PACK
        SELECT SKLAD
        RETURN
   ENDIF

   NKOL_P = KOL_ST
   SELECT SKLAD
   REPLACE OS_ST WITH OS_ST - NKOL_P

RETURN

**************************
****DENSHNA DATA I SUMA********
FUNCTION SUM_D
REPLACE DATAP_ST WITH DATE()
REPLACE SUMA_ST WITH KOL_ST*PEDC_ST
RETURN .t.

**************************************






**************************************
****NOMER NA obekt   **********

FUNCTION MNOMER(_NOM)
sRETURN=.T.
IF _NOM =0
        sRETURN=.F.
ELSE
        SELECT MG
        GO TOP
        SEEK _NOM
        IF FOUND()
                vNOM_MAG = NOM_MAG
                SELECT MAG
                REPLACE NOM_MAG WITH vNOM_MAG
        ELSE
                sRETURN = .F.
        ENDIF
ENDIF

SELECT MAG

RETURN sRETURN
**************************************************
******** func ONBEHEPA ****
FUNCTION ONBEHEPA()
SET KEY -1 TO BEHEPA()
RETURN .T.


**************************************************

**************************************************
******** func OffBENEPA ****
FUNCTION OffBEHEPA()
SET KEY -1
RETURN .T.


**************************************************
******** func Pluton ****

FUNCTION BEHEPA()

SET KEY -1
TRK = RECNO()
SELECT MG
   Mst :=    {'NOM_MAG', 'IME_MAG',  'ADRES'  ,'PROD1' , 'PROD2' , 'PROD3' , 'PROD4' , 'ZABEL'}
   MNamest :={'Õ','€ˆŒ…Ž‚€ˆ…','€„…‘', 'Ž„€‚€— 1' ,'Ž„€‚€— 2' ,'Ž„€‚€— 3' ,'Ž„€‚€— 4' ,'‡€…‹…†Š€'}

   DEFI WIND WinMM FROM 4 ,40  TO 21 ,78 TITLE "ŽŒ…Š‹€’“€ Ž…Š’ˆ";
   'ðÍÑÍÈÇ' FLOAT SHADOW
   ACTIVATE WINDOW WinMM
        DBEDIT( 1, 0,13,36,Mst,'dbeBEHEPA',NIL,MNamest,"Ä"," ","Ä")

   SELECT MAG
   GO TRK
   RELEASE WINDOW WinMM
   set cursor on
   SET KEY -1 TO BEHEPA()
RETURN .T.


**************************************************
******** func dbeBEHEPA ****
FUNCTION dbeBEHEPA(mode,dPeek1)
  l_key := LASTKEY()  && —¥²¥¬ ¯®±«¥¤­¨¿² ­ ²¨±­ ² ª« ¢¨¸
  nROW := ROW()       &&  ¬¨° ¬¥ ªº¤¥ ¥ ¡¨« ¬ °ª¥° 
  nCOL := COL()       &&
  nreturn:=1


  DO CASE
     CASE  mode = 0
      @ (WROWS(WoUtput())-4),0 say space(35)
      @ (WROWS(WoUtput())-4),0 SAY '‡ ¯¨± ­®¬¥° '+STR(RECNO(),5) +'/' + LTRIM(STR(RECCOUNT()))+ ;
      " Š®«®­  "+ALLTRIM(str(ncol))+" ¥¤ "+ALLTRIM(str(nrow))
      @ (WROWS(WoUtput())-5),0 SAY 'ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ'
     CASE mode=1
        @ 2,2 SAY '„®±²¨£­ ²® ¥ ­ · «®²® ­  ´ ©« '
        INKEY(0)
        @ 2,2 SAY 'ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ'
        nreturn:=1
     CASE mode=2
        @ 2,2 SAY   '„®±²¨£­ ² ¥ ª° ¿ ­  ´ ©« .  '
        inkey(0)
        @ 2,2 SAY   'ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ'
        nreturn:=2

     CASE  l_key = _ESC && EXIT <<--------------------------------
        nReturn := 0
*******************                ª® ¿¬  § ¯¨±¨ ¢º¢ ”€ˆ‹€ MMAIN1.DBF
     CASE  l_key = _RETURN
          P1NOM = NOM_MAG
          SELECT MAG
          REPLACE NOM_MAG WITH P1NOM
          nReturn := 0
     CASE  l_key = _DEL  // iztriva zapis posle sloji syobchteniq
           delete
           pack
           nReturn := 2

     CASE  l_key = _F3   // iztriva zapis posle sloji syobchteniq

        DEFI WIND WinIM2 FROM 4 ,20  TO 14 ,70 TITLE " ŠŽ…Š–ˆŸ € ŽŒ…Š‹€’“€ ";
        'ðÍÑÍÈÇ' FLOAT SHADOW
        ACTIVATE WINDOW WinIM2

        SET CURSOR ON
        SET ESCAPE ON
        set color to ,,,,,W+/N

        neda = NOM_MAG

        REPLACE NOM_MAG WITH neda
        ppNOM_MG = NOM_MAG
        @ 1,1  SAY 'ŽŒ…:       ' + STR(ppNOM_MG)
        @ 2,1  SAY '€ˆŒ…Ž‚€ˆ…:'  GET IME_MAG
        @ 3,1  SAY '€„…‘:       '  GET ADRES
        @ 4,1  SAY 'Ž„€‚€— 1:  '  GET PROD1
        @ 5,1  SAY 'Ž„€‚€— 2:  '  GET PROD2
        @ 6,1  SAY 'Ž„€‚€— 3:  '  GET PROD3
        @ 7,1  SAY 'Ž„€‚€— 4:  '  GET PROD4
        @ 8,1  SAY '‡€…‹…†Š€:   '  GET ZABEL
        READ
        replace NOM_MAG with ppNOM_MG
        SET COLOR TO
        SET CURSOR off
        RELEASE WINDOW WinIM2
*       restgets()
        nreturn:=2

     CASE l_key  = _INS .or. mode=3 && PAD ¢º¢¥¦¤ ­¥
        savegets()

        DEFI WIND WinIM FROM 4 ,20  TO 14 ,78 TITLE " ‚º¢¥¦¤ ­¥ ­  ­®¢  ­®¬¥­ª« ²³°  ";
        'ðÍÑÍÈÇ' FLOAT SHADOW
        ACTIVATE WINDOW WinIM


        SET CURSOR ON
        SET ESCAPE ON
        set color to ,,,,,W+/N

        SELECT MG
        SET INDEX TO
        GO BOTTOM
        neda = 0
        neda = NOM_MAG + 1
        SELECT MG
        SET INDEX TO NOMMG
        APPEND BLANK

        REPLACE NOM_MAG WITH neda
        ppNOM_MG = NOM_MAG
        @ 1,1  SAY 'ŽŒ…:       '  GET ppNOM_MG // valid(PRMG_ins(ppNOM_MG))
        @ 2,1  SAY '€ˆŒ…Ž‚€ˆ…:'  GET IME_MAG
        @ 3,1  SAY '€„…‘:       '  GET ADRES
        @ 4,1  SAY 'Ž„€‚€— 1:  '  GET PROD1
        @ 5,1  SAY 'Ž„€‚€— 2:  '  GET PROD2
        @ 6,1  SAY 'Ž„€‚€— 3:  '  GET PROD3
        @ 7,1  SAY 'Ž„€‚€— 4:  '  GET PROD4
        @ 8,1  SAY '‡€…‹…†Š€:   '  GET ZABEL
        READ
        replace NOM_MAG with ppNOM_MG
        IF LASTKEY() = _ESC
                DELETE
                PACK
        ENDIF
        SET COLOR TO
        SET CURSOR off
        RELEASE WINDOW WinIM
        restgets()

        nreturn:=2

        OTHERWISE
        nreturn:=2
     endCASE

return nReturn

*******************************************
******* funktion PRMG_ins(NOM_MAG) // proverqva za dublirane na imena
FUNCTION PRMG_ins(tr_NOM)
pozres = recno()
pRETURN = .T.
GO TOP
locate for tr_NOM=NOM_MAG
if found()
   pRETURN = .f.
   inkey(0)
   vz_error("„³¡«¨° ­¥ ­  ª®¤. OP ERROR","Œ®«¿ ª®°¥£¨° ©²¥ ..  ")
endif
go pozres
return pRETURN
*** end of functio seact nom
************************************************************************
************************************************************************

**************************************
**************** pregled() -----------  nalichnosti v magazin
FUNCTION Pregled()
   BAZE=ALIAS()
   select mag
                DEFI WIND db_ww4 FROM 6 ,25 TO 13,75 TITLE " …Š€€ ‘€‚Š€ ‘’ŽŠ€ ‚ Ž…Š’: ";
                'ÚÄÏÓÙÄÀÓ' FLOAT SHADOW
                ACTIVATE WINDOW db_ww4
                LP = 0
                DO WHILE LP=0 .AND. LASTKEY()<>_ESC
                        g_Nom  = 00
                        gN_DATE = DATE()
                        gK_DATE = DATE()
                        @ 1,0  SAY 'ŽŒ… € Ž…Š’: ' GET g_Nom
                        @ 2,0  SAY '€—€‹€ „€’€ ‡€ ‘€‚Š€: ' GET gN_DATE
                        @ 3,0  SAY 'Š€‰€ „€’€ ‡€ ‘€‚Š€ : ' GET gK_DATE
                        READ
                        IF g_Nom>0
                                LOCATE FOR NOM_MAG=g_Nom
                                IF FOUND()
                                        GO TOP
                                        SET FILTER TO NOM_MAG=g_Nom .AND. DATAP_ST>=gN_DATE .AND. DATAP_ST<=gK_DATE
                                        GO BOTTOM
                                        GO TOP
                                        LP=1
                                ELSE
                                        DO no_zap
                                ENDIF
                        ENDIF
                ENDDO
                RELEASE WINDOW db_ww4




   mPst :=    {'NOM_MAG','NOM_ST' , 'IME_ST',     'MER_ST','Kol_st'    ,'Pedc_st','Suma_st'         ,'datap_st','Zabel'}
   mPNamest :={'ÕŽ. '  ,'Õ‘’ŽŠ€ ','€ˆŒ…Ž‚€ˆ…','Œ.….'  ,'Š®«. ±²®ª ','…¤.¶¥­ ','Ž¡¹²  ±²®¨­®±²','„ ² '    ,'‡ ¡¥«¥¦ª '}

   DEFI WIND WinSP FROM 6 ,1  TO 23 ,78 TITLE " §¯°¥¤¥«¥­¨ ‘’ŽŠˆ ¯® ®¡¥ª²¨";
   'ðÍÑÍÈÇ' FLOAT SHADOW
   ACTIVATE WINDOW WinSP

        DBEDIT( 1, 0,13,75,mPst,'dbeOBECT',NIL,mPNamest,"Ä"," ","Ä")
         ***********************function dbedit




         SET FILTER TO
   RELEASE WINDOW WinSP
   select &Baze
return .t.



**************************************
**************** Pari() ---------->  otcheteni ot magazin
FUNCTION Pari()
   BAZE=ALIAS()
   select MONEY
   mPst :=    {'NOM_MAG','OBEKT_IME' , 'PARI',     'DATA'}
   mPNamest :={'ÕŒ€ƒ.'  ,'Œ€ƒ€‡ˆ','Ž™’€ ‘’ŽˆŽ‘’','„€’€'}

   DEFI WIND WinPARI FROM 6 ,1  TO 23 ,78 TITLE "Ž²·¥²¥­¨ ¯ °¨ ®² Œ€ƒ€‡ˆ";
   'ðÍÑÍÈÇ' FLOAT SHADOW
   ACTIVATE WINDOW WinPARI
        DBEDIT( 1, 0,13,75,mPst,'dbePARI',NIL,mPNamest,"Ä"," ","Ä")
         ***********************function dbedit
   RELEASE WINDOW WinPARI
   select &Baze
return .t.


**************************************************
******** func dbePARI ****
FUNCTION dbePARI(mode,dPeek1)
  l_key := LASTKEY()  && —¥²¥¬ ¯®±«¥¤­¨¿² ­ ²¨±­ ² ª« ¢¨¸
  nROW := ROW()       &&  ¬¨° ¬¥ ªº¤¥ ¥ ¡¨« ¬ °ª¥° 
  nCOL := COL()       &&
  nreturn:=1


  DO CASE
     CASE  mode = 0
      @ (WROWS(WoUtput())-4),0 say space(35)
      @ (WROWS(WoUtput())-4),0 SAY '‡ ¯¨± ­®¬¥° '+STR(RECNO(),5) +'/' + LTRIM(STR(RECCOUNT()))+ ;
      " Š®«®­  "+ALLTRIM(str(ncol))+" ¥¤ "+ALLTRIM(str(nrow))
      @ (WROWS(WoUtput())-5),0 SAY 'ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ'
     CASE mode=1
        @ 2,2 SAY '„®±²¨£­ ²® ¥ ­ · «®²® ­  ´ ©« '
        INKEY(0)
        @ 2,2 SAY 'ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ'
        nreturn:=1
     CASE mode=2
        @ 2,2 SAY   '„®±²¨£­ ² ¥ ª° ¿ ­  ´ ©« .  '
        inkey(0)
        @ 2,2 SAY   'ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ'
        nreturn:=2

     CASE  l_key = _ESC && EXIT <<--------------------------------
        nReturn := 0
*******************                ª® ¿¬  § ¯¨±¨ ¢º¢ ”€ˆ‹€ money.dbf
*?????????******* korekcii
     CASE  l_key = _RETURN
          P1NOM = NOM_MAG
          SELECT MONEY
        SET CURSOR ON
        SET ESCAPE ON
        set color to ,,,,,W+/N
        @ (WROWS(WoUtput())-3),0 SAY '¥¦¨¬ Š®°¥£¨° ­¥ ­  Ž’—…’'
        @ (WROWS(WoUtput())-5),0 SAY space(60)

        DEFI WIND WinKO FROM 2 ,4   TO 14 ,55 TITLE " Š®°¥£¨° ­¥ ­  Ž’—…’ ";
        'ðÍÑÍÈÇ' FLOAT SHADOW
        ACTIVATE WINDOW WinKO
        set color to ,,,,,W+/N
        pNOM_MAG  = NOM_MAG
        pOBEKT_IME= OBEKT_IME
        pPARI     = PARI
        pDATA     = DATA

        @ 1,2 SAY 'ŽŒ…:      ' GET NOM_MAG
        @ 2,2 SAY 'Ž…Š’ ˆŒ…:  ' GET OBEKT_IME
        @ 3,2 SAY '‘“Œ€:       ' GET PARI
        @ 4,2 SAY '„€’€:       ' GET DATA
        READ

        if LastKey() = _ESC
           replace NOM_MAG   with  pNOM_MAG
           replace OBEKT_IME with  pOBEKT_IME
           replace PARI      with  pPARI
           replace DATA      with  pDATA
        endif
        SET COLOR TO
        RELEASE WINDOW WinKO
        SET CURSOR OFF
        nReturn :=  2
****************** end korekcii

     CASE  l_key = _DEL  // iztriva zapis posle sloji syobchteniq
           delete
           pack
           nReturn := 2
     CASE l_key  = _INS .or. mode=3 && PAD ¢º¢¥¦¤ ­¥
        savegets()

        DEFI WIND WinPARI2 FROM 4 ,20  TO 14 ,78 TITLE " ‚º¢¥¦¤ ­¥ ­  Ž’—…’…ˆ €ˆ ";
        'ðÍÑÍÈÇ' FLOAT SHADOW
        ACTIVATE WINDOW WinPARI2


        SET CURSOR ON
        SET ESCAPE ON
        set color to ,,,,,W+/N

        SELECT MONEY
        SET INDEX TO MONY
        vNOM_MAG = 00
        vSUMA = 000000000000
        vDATA = DATE()

        @ 1,1  SAY 'ŽŒ…:       '  GET vNOM_MAG
        READ
        SELECT MG
        SET INDEX TO NOMMG
        SEEK vNOM_MAG
        IF FOUND()
                vIME_MAG = IME_MAG
        ENDIF
        SELECT MONEY
        @ 2,1  SAY '€ˆŒ…Ž‚€ˆ…:'  GET vIME_MAG
        @ 3,1  SAY '‘“Œ€:        '  GET vSUMA
        @ 4,1  SAY '„€’€:        '  GET vDATA
        READ

        APPEND BLANK
        REPLACE NOM_MAG WITH vNOM_MAG
        REPLACE OBEKT_IME WITH vIME_MAG
        REPLACE PARI WITH vSUMA
        REPLACE DATA WITH vDATA

        IF LASTKEY() = _ESC
                DELETE
                PACK
        ENDIF
        SET COLOR TO
        SET CURSOR off
        RELEASE WINDOW WinPARI2
        restgets()

        nreturn:=2

        OTHERWISE
        nreturn:=2
     endCASE

return nReturn
**********************************


******************************** spravka stoki v MAGAZIN *************
PROCEDURE Spr_st_mag()
                Baze=ALIAS()
                SELECT MAG
                DEFI WIND db_ww FROM 6 ,25 TO 11,75 TITLE " …—€’€ ‘€‚Š€ ‘’ŽŠˆ ‚ Œ€ƒ€‡ˆ: ";
                'ÚÄÏÓÙÄÀÓ' FLOAT SHADOW
                ACTIVATE WINDOW db_ww
                LP = 0
                DO WHILE LP=0 .AND. LASTKEY()<>_ESC
                        g_Nom  = 00
                        g_DATE = DATE()
                        @ 1,0  SAY 'ŽŒ… € Œ€ƒ€‡ˆ: ' GET g_Nom
                        @ 2,0  SAY '„€’€ ‡€ ‘€‚Š€: ' GET g_DATE
                        READ
                        RELEASE WINDOW db_ww
                        IF g_Nom>0
                                LOCATE FOR NOM_MAG=g_Nom
                                IF FOUND()
                                        DO f_prt1
                                        LP=1
                                        DO prt_pr
                                ELSE
                                        DO no_zap
                                ENDIF
                        ENDIF
                ENDDO
                SELECT &Baze

********************************* ”ŽŒ“‹Ÿ ‡€ …—€’ 1 stoki v magazin *****************************
PROCEDURE  f_prt1
SET PRINTER ON
SET DEVICE TO PRINT
@ pROW()+1, 8 SAY '            ‘€‚Š€ ‡€ …•‚š‹…ˆ ‘’ŽŠˆ ‚ Ž…Š’ Õ ' + STR(NOM_MAG)
@ pROW()+1, 8 SAY ' '
@ pROW()+1, 3 SAY ' € „€’€: ' + DTOC(g_DATE)
SET FILTER TO NOM_MAG=g_Nom .AND. DATAP_ST=g_DATE
GO TOP
        @ pROW()+1, 3 SAY 'ÚÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÏ'
        @ pROW()+1, 3 SAY 'ÓÕ ‘’ŽŠ€Ó   ˆŒ… € ‘’ŽŠ€’€   ÓŒ…€ …„.ÓŠŽ‹ˆ—…‘’‚ŽÓ …„.–…€ Ó   ‘“Œ€    Ó'
        @ pROW()+1, 3 SAY 'ÃÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÔ'
        DO WHILE !EOF()
                @ pROW()+1, 3 SAY 'Ó  ' + STR(NOM_ST) + ' Ó' + IME_ST + 'Ó' + MER_ST + '   Ó ' + STR(KOL_ST) + 'Ó' + STR(PEDC_ST) + 'Ó' + STR(SUMA_ST) + 'Ó'
                SKIP +1
        ENDDO
        @ pROW()+1, 3 SAY 'ÀÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÙ'

SET PRINTER OFF
SET DEVICE TO SCREEN
RETURN


************************ ŸŒ€ ’€Šš‚ ‡€ˆ‘ ***************************
PROCEDURE  no_zap
        DEFI WIND db_wse FROM 6 ,23 TO 10,58 TITLE " ‘ˆ‘’…Œ€ ƒ…˜Š€!!! ";
                       'ÚÄÏÓÙÄÀÓ' FLOAT SHADOW COLOR SCHEME 8
        ACTIVATE WINDOW db_wse
        @ 1, 8 SAY 'ŸŒ€ ’€Šš‚ ‡€ˆ‘ !'
        SET CURSOR OFF
        INKEY(0)
        SET CURSOR ON
        RELEASE WIND db_wse
RETURN


************************ prt_pr ***************************
PROCEDURE prt_pr



RETURN


******************************** spravka stojnost na stoka v MAGAZIN ********
PROCEDURE Spr_ostst_mag()
                Baze=ALIAS()
                SELECT MAG
                DEFI WIND db_ww2 FROM 6 ,25 TO 13,75 TITLE " ‘€‚Š€ ‘’Ž‰Ž‘’ € ‘’ŽŠ€ ‚ Œ€ƒ€‡ˆ: ";
                'ÚÄÏÓÙÄÀÓ' FLOAT SHADOW
                ACTIVATE WINDOW db_ww2
                LP = 0
                DO WHILE LP=0 .AND. LASTKEY()<>_ESC
                        g_Nom  = 00
                        gN_DATE = DATE()
                        gK_DATE = DATE()
                        @ 1,0  SAY 'ŽŒ… € Œ€ƒ€‡ˆ: ' GET g_Nom
                        @ 2,0  SAY '€—€‹€ „€’€ ‡€ ‘€‚Š€: ' GET gN_DATE
                        @ 3,0  SAY 'Š€‰€ „€’€ ‡€ ‘€‚Š€ : ' GET gK_DATE
                        READ
                        vSUMA = 0
                        IF g_Nom>0
                                LOCATE FOR NOM_MAG=g_Nom
                                IF FOUND()
                                        GO TOP
                                        SUM ALL SUMA_ST TO vSUMA FOR (NOM_MAG=g_Nom .AND. DATAP_ST>=gN_DATE .AND. DATAP_ST<=gK_DATE)
                                        @ 4,0  SAY '‘“Œ€: ' + STR(vSUMA)
                                        INKEY(0)
                                        LP=1
                                ELSE
                                        DO no_zap
                                ENDIF
                        ENDIF
                ENDDO
                RELEASE WINDOW db_ww2
                SELECT &Baze
RETURN

******************************** spravka otcheteni pari ot MAGAZIN ***********
PROCEDURE Spr_otpar_mag()
                Baze=ALIAS()
                SELECT MONEY
                DEFI WIND db_ww3 FROM 6 ,25 TO 13,75 TITLE " ‘€‚Š€ Ž’—…’…ˆ €ˆ Ž’ Œ€ƒ€‡ˆ: ";
                'ÚÄÏÓÙÄÀÓ' FLOAT SHADOW
                ACTIVATE WINDOW db_ww3
                LP = 0
                DO WHILE LP=0 .AND. LASTKEY()<>_ESC
                        g_Nom  = 00
                        gN_DATE = DATE()
                        gK_DATE = DATE()
                        @ 1,0  SAY 'ŽŒ… € Œ€ƒ€‡ˆ: ' GET g_Nom
                        @ 2,0  SAY '€—€‹€ „€’€ ‡€ ‘€‚Š€: ' GET gN_DATE
                        @ 3,0  SAY 'Š€‰€ „€’€ ‡€ ‘€‚Š€ : ' GET gK_DATE
                        READ
                        vSUMA = 0
                        IF g_Nom>0
                                LOCATE FOR NOM_MAG=g_Nom
                                IF FOUND()
                                        GO TOP
                                        SUM ALL PARI TO vSUMA FOR (NOM_MAG=g_Nom .AND. DATA>=gN_DATE .AND. DATA<=gK_DATE)
                                        @ 4,0  SAY '‘“Œ€: ' + STR(vSUMA)
                                        INKEY(0)
                                        LP=1
                                ELSE
                                        DO no_zap
                                ENDIF
                        ENDIF
                ENDDO
                RELEASE WINDOW db_ww3
                SELECT &Baze
RETURN
***************************



**************************************************
******** func dbeOBECT ****
FUNCTION dbeOBECT(mode,dPeek1)
  l_key := LASTKEY()  && —¥²¥¬ ¯®±«¥¤­¨¿² ­ ²¨±­ ² ª« ¢¨¸
  nROW := ROW()       &&  ¬¨° ¬¥ ªº¤¥ ¥ ¡¨« ¬ °ª¥° 
  nCOL := COL()       &&
  nreturn:=1


  DO CASE
     CASE  mode = 0
      @ (WROWS(WoUtput())-4),0 say space(35)
      @ (WROWS(WoUtput())-4),0 SAY '‡ ¯¨± ­®¬¥° '+STR(RECNO(),5) +'/' + LTRIM(STR(RECCOUNT()))+ ;
      " Š®«®­  "+ALLTRIM(str(ncol))+" ¥¤ "+ALLTRIM(str(nrow))
      @ (WROWS(WoUtput())-5),0 SAY 'ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ'
     CASE mode=1
        @ 2,2 SAY '„®±²¨£­ ²® ¥ ­ · «®²® ­  ´ ©« '
        INKEY(0)
        @ 2,2 SAY 'ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ'
        nreturn:=1
     CASE mode=2
        @ 2,2 SAY   '„®±²¨£­ ² ¥ ª° ¿ ­  ´ ©« .  '
        inkey(0)
        @ 2,2 SAY   'ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ'
        nreturn:=2

     CASE  l_key = _ESC && EXIT <<--------------------------------
        nReturn := 0
*******************                ª® ¿¬  § ¯¨±¨ ¢º¢ ”€ˆ‹€

*******************  korekciq .....
     CASE L_key = _RETURN  // korekciq
        SELECT MAG
        SET CURSOR ON
        SET ESCAPE ON
        set color to ,,,,,W+/N
        @ (WROWS(WoUtput())-3),0 SAY '  ¥¦¨¬ Š®°¥£¨° ­¥ ­   ±²®ª .'
        @ (WROWS(WoUtput())-5),0 SAY space(60)

        DEFI WIND WinAA FROM 2 ,4   TO 14 ,55 TITLE "  Š®°¥£¨° ­¥ ­   ±²®ª   ";
        'ðÍÑÍÈÇ' FLOAT SHADOW
        ACTIVATE WINDOW WinAA
        set color to ,,,,,W+/N
        SET KEY -1 TO Pluton // seen bot za nomenklaturata
        pNOM_ST   = NOM_ST
        pIME_ST   = IME_ST
        pMER_ST   = MER_ST
        pKOL_ST   = KOL_ST
        pEDCP_ST  = EDCP_ST
        pSUMA_ST  = SUMA_ST
        pDATAP_ST = DATAP_ST
        pPEDC_ST  = PEDC_ST
        pOS_ST    = OS_ST
        pZABEL    = ZABEL
        @ 1,2 SAY 'ŽŒ…       ' GET NOM_ST   WHEN(ONPLUTON()) VALID(SNOMER(NOM_ST))
        @ 2,2 SAY 'ˆŒ…         ' GET IME_ST   WHEN(OffPluton())
        @ 3,2 SAY 'Œ.….        ' GET MER_ST
        @ 4,2 SAY 'ŠŽ‹ˆ—…‘’‚Ž  ' GET KOL_ST   VALID(KOL_ST  > 0)
        @ 5,2 SAY '…„.–…€     ' GET EDCP_ST  VALID(EDCP_ST > 0)
        @ 6,2 SAY '‘“Œ€        ' GET SUMA_ST  WHEN(K_SBOR(pKOL_ST,pOS_ST))
        @ 7,2 SAY '„€’€        ' GET DATAP_ST
        @ 8,2 SAY 'Ž„.…„.–…€' GET PEDC_ST  VALID(PEDC_ST > 0)
        @ 9,2 SAY '‡€…‹E†Š€   ' GET ZABEL
        READ
        if LastKey() = _ESC
           replace NOM_ST   with  pNOM_ST
           replace IME_ST   with  pIME_ST
           replace MER_ST   with  pMER_ST
           replace KOL_ST   with  pKOL_ST
           replace EDCP_ST  with  pEDCP_ST
           replace SUMA_ST  with  pSUMA_ST
           replace DATAP_ST with  pDATAP_ST
           replace PEDC_ST  with  pPEDC_ST
           replace OS_ST    with  pOS_ST
           replace ZABEL    with  pZABEL
           set key -1
        endif
        SET COLOR TO
        RELEASE WINDOW WinAA
        SET CURSOR OFF
        nReturn := 0

     CASE  l_key = _DEL  // iztriva zapis posle sloji syobchteniq
           delete
           pack
           nReturn := 2

     CASE  l_key = _F9   // prehvyrlja pari
           MAGAZIN3()
           nReturn := 2

     CASE  l_key = _F10  // prehvyrlja stoka
           MAGAZIN2()
           nReturn := 2

     endCASE

return nReturn



***Ž–…„“€ ‡€ €‡…„…‹…ˆ… € ‘’ŽŠˆ**********
**********************************************
PROCEDURE MAGAZIN2()

   DEFI WIND Win_MG FROM 5 ,4   TO 20 ,55 TITLE " €‡…„…‹…ˆ… Ž’ Ž…Š’ ";
   'ðÍÑÍÈÇ' FLOAT SHADOW
   ACTIVATE WINDOW Win_MG
   NOM_P = NOM_ST
   IME_P = IME_ST
   MER_P = MER_ST
   PEDC_P = PEDC_ST
   KOL_P = OS_ST
   SELECT MAG
   APPEND BLANK
   REPLACE NOM_ST WITH NOM_P
   REPLACE IME_ST WITH IME_P
   REPLACE MER_ST WITH MER_P
   REPLACE PEDC_ST WITH PEDC_P

   @0,1 SAY 'Ž…Š’ ŽŒ…:' GET NOM_MAG WHEN(ONBEHEPA()) VALID(MNOMER(NOM_MAG))
   @1,1 SAY 'ŠŽ‹ˆ—…‘’‚Ž:   ' GET KOL_ST  WHEN(OffBEHEPA()) VALID(KOL_ST > 0 .AND. KOL_ST <= KOL_P)
   @1,26 SAY 'Ž‘’€’šŠ:' + STR(KOL_P)
   @2,1 SAY 'Ž„.…„.–…€: ' GET PEDC_ST VALID(PEDC_ST>0)
   @3,1 SAY '‘“Œ€:         ' GET SUMA_ST WHEN(SUM_D())
   @4,1 SAY '„€’€:         ' GET DATAP_ST
   @5,1 SAY '‡€…‹…†Š€:    ' GET ZABEL
   READ
   OffBEHEPA()
   RELEASE WINDOW Win_MG
   IF LASTKEY() = _ESC
        DELETE
        PACK
        RETURN
   ENDIF

   NKOL_P = KOL_ST
******sklad
   REPLACE OS_ST WITH OS_ST - NKOL_P

RETURN


***Ž–…„“€ ‡€ …•‚š‹Ÿ… € €ˆ**********
**********************************************
PROCEDURE MAGAZIN3()

   DEFI WIND Win_MG FROM 5 ,4   TO 10 ,55 TITLE " …•‚š‹Ÿ €ˆ Ž’ Ž…Š’ ";
   'ðÍÑÍÈÇ' FLOAT SHADOW
   ACTIVATE WINDOW Win_MG

   LV = 0
   DATA=DATE()
   @ 1,3 SAY 'ŠŽ‹ŠŽ ‹…‚€ „€ š„€’ Ž’—…’…ˆ:' GET LV
   @ 2,3 SAY '                        „€’€:' GET DATA
   READ

   OffBEHEPA()
   RELEASE WINDOW Win_MG

   SELECT MAG
   REPLACE PEDC_ST WITH (SUMA_ST / KOL_ST)
   REPLACE SUMA_ST WITH (SUMA_ST - LV)
   REPLACE KOL_ST WITH (SUMA_ST / PEDC_ST)

   pNOM_MAG  = NOM_MAG

   SELECT MG
   SEEK pNOM_MAG

   IF FOUND()
        pOBEKT_IME= IME_MAG
   ELSE
        pOBEKT_IME= " "
   ENDIF

   pPARI     = LV
   pDATA     = DATA

   SELECT MONEY
        if LastKey() != _ESC
           GO BOTTOM
           APPEND BLANK
           replace NOM_MAG   with  pNOM_MAG
           replace OBEKT_IME with  pOBEKT_IME
           replace PARI      with  pPARI
           replace DATA      with  pDATA
        endif
   SELECT MAG

RETURN

